name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mr-smithers-excellent/docker-build-push@v6
    - name: Build and push the Docker image
    - with:
      image: nodes-lamb
      registry: ghcr.io
      username: ${{ secrets.GHCR_USERNAME }}
      password: ${{ secrets.GHCR_TOKEN }}
